import Navber from "@/src/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/src/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Limamia",
  description: "Generated by Omar chowdhury",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto min-h-screen flex flex-col justify-between ">
          <Navber />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
